"""Add google auth

Revision ID: 0b2822fc96c2
Revises: fe1d1915b4d4
Create Date: 2026-03-23 15:05:56.514232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0b2822fc96c2'
down_revision: Union[str, Sequence[str], None] = 'fe1d1915b4d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_sub", sa.String(), nullable=True))
    op.add_column("users", sa.Column("auth_provider", sa.String(), nullable=False, server_default="local"))

    op.alter_column("users", "password", existing_type=sa.String(), nullable=True)
    op.alter_column("users", "city", existing_type=sa.String(), nullable=False, server_default="")
    op.alter_column("users", "country", existing_type=sa.String(), nullable=False, server_default="")

    op.create_unique_constraint("uq_users_google_sub", "users", ["google_sub"])

    op.alter_column("users", "auth_provider", existing_type=sa.String(), server_default=None)
    op.alter_column("users", "country", existing_type=sa.String(), server_default=None)
    op.alter_column("users", "city", existing_type=sa.String(), server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_users_google_sub", "users", type_="unique")

    op.alter_column("users", "city", existing_type=sa.String(), nullable=False, server_default="")
    op.alter_column("users", "country", existing_type=sa.String(), nullable=False, server_default="")
    op.alter_column("users", "auth_provider", existing_type=sa.String(), nullable=False, server_default="local")
    op.alter_column("users", "password", existing_type=sa.String(), nullable=False)

    op.drop_column("users", "auth_provider")
    op.drop_column("users", "google_sub")

    op.alter_column("users", "country", existing_type=sa.String(), server_default=None)
    op.alter_column("users", "city", existing_type=sa.String(), server_default=None)
    # ### end Alembic commands ###
