"""sprint statuses

Revision ID: 3384cb8e2cdb
Revises: 5eee3e300c61
Create Date: 2026-03-31 20:38:41.403339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3384cb8e2cdb'
down_revision: Union[str, Sequence[str], None] = '5eee3e300c61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "sprint",
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            server_default="PLANNED",
        ),
    )
    op.execute("""
        UPDATE sprint
        SET status = CASE
            WHEN end_date < NOW() THEN 'COMPLETED'
            WHEN start_date <= NOW() AND end_date >= NOW() THEN 'ACTIVE'
            ELSE 'PLANNED'
        END
    """)

    op.alter_column("sprint", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sprint", "status")
    # ### end Alembic commands ###
