"""add kanban states to tasks

Revision ID: 5eee3e300c61
Revises: 0b2822fc96c2
Create Date: 2026-03-31 19:46:47.275033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eee3e300c61'
down_revision: Union[str, Sequence[str], None] = '0b2822fc96c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "task",
        sa.Column(
            "workflow_status",
            sa.String(),
            nullable=False,
            server_default="TODO",
        ),
    )
    op.add_column(
        "task",
        sa.Column(
            "board_order",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.execute("UPDATE task SET workflow_status = 'TODO' WHERE workflow_status IS NULL")
    op.execute("UPDATE task SET board_order = 0 WHERE board_order IS NULL")

    op.alter_column("task", "workflow_status", server_default=None)
    op.alter_column("task", "board_order", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "board_order")
    op.drop_column("task", "workflow_status")
    # ### end Alembic commands ###
