"""_add_task_multiple_assingees

Revision ID: 6053296d6ac9
Revises: 8e55e72db07a
Create Date: 2026-05-01 02:55:40.008262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6053296d6ac9'
down_revision: Union[str, Sequence[str], None] = '8e55e72db07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_multiple_assignees',
    sa.Column('id_task_multiple_assignees', sa.Integer(), nullable=False),
    sa.Column('fk_userid_user', sa.Integer(), nullable=False),
    sa.Column('fk_taskid_task', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_taskid_task'], ['task.id_task'], ),
    sa.ForeignKeyConstraint(['fk_userid_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_task_multiple_assignees')
    )
    op.create_index(op.f('ix_task_multiple_assignees_id_task_multiple_assignees'), 'task_multiple_assignees', ['id_task_multiple_assignees'], unique=False)
    op.add_column(
    'task',
    sa.Column('multiplePeople', sa.Boolean(), nullable=False, server_default=sa.false())
)



def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('task', 'multiplePeople')
    op.drop_index(op.f('ix_task_multiple_assignees_id_task_multiple_assignees'), table_name='task_multiple_assignees')
    op.drop_table('task_multiple_assignees')
    # ### end Alembic commands ###
