"""baseline schema

Revision ID: bb2dea7b4a78
Revises: 
Create Date: 2026-03-02 16:50:41.855643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb2dea7b4a78'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("""
    CREATE TABLE project (
        name varchar,
        description varchar,
        id_project integer GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id_project)
    );

    CREATE TABLE retrospective (
        text text,
        id_retrospective integer GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id_retrospective)
    );

    CREATE TABLE role_enum (
        id_role_enum integer GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id_role_enum)
    );

    CREATE TABLE users (
        name varchar,
        email varchar,
        country varchar,
        city varchar,
        password varchar,
        id_user integer GENERATED BY DEFAULT AS IDENTITY,
        PRIMARY KEY (id_user)
    );

    CREATE TABLE role (
        visibility int,
        id_role integer GENERATED BY DEFAULT AS IDENTITY,
        fk_projectid_project integer NOT NULL,
        PRIMARY KEY (id_role),
        CONSTRAINT has FOREIGN KEY (fk_projectid_project)
            REFERENCES project (id_project)
    );

    CREATE TABLE team (
        name varchar,
        id_team integer GENERATED BY DEFAULT AS IDENTITY,
        fk_projectid_project integer NOT NULL,
        PRIMARY KEY (id_team),
        CONSTRAINT team_belongs FOREIGN KEY (fk_projectid_project)
            REFERENCES project (id_project)
    );

    CREATE TABLE project_member (
        role varchar,
        id_project_member integer GENERATED BY DEFAULT AS IDENTITY,
        fk_userid_user integer NOT NULL,
        fk_projectid_project integer NOT NULL,
        fk_roleid_role integer NOT NULL,
        PRIMARY KEY (id_project_member),
        CONSTRAINT is_a FOREIGN KEY (fk_userid_user)
            REFERENCES users (id_user),
        CONSTRAINT of_this FOREIGN KEY (fk_projectid_project)
            REFERENCES project (id_project),
        CONSTRAINT has_a FOREIGN KEY (fk_roleid_role)
            REFERENCES role (id_role)
    );

    CREATE TABLE team_member (
        effectiveness int,
        role_in_team varchar,
        id_team_member integer GENERATED BY DEFAULT AS IDENTITY,
        fk_teamid_team integer NOT NULL,
        fk_userid_user integer NOT NULL,
        PRIMARY KEY (id_team_member),
        CONSTRAINT is_member FOREIGN KEY (fk_teamid_team)
            REFERENCES team (id_team),
        CONSTRAINT is_user FOREIGN KEY (fk_userid_user)
            REFERENCES users (id_user)
    );

    CREATE TABLE sprint (
        start_date timestamp,
        end_date timestamp,
        id_sprint integer GENERATED BY DEFAULT AS IDENTITY,
        fk_teamid_team integer NOT NULL,
        fk_retrospectiveid_retrospective integer NOT NULL,
        PRIMARY KEY (id_sprint),
        UNIQUE (fk_retrospectiveid_retrospective),
        CONSTRAINT has_sprint FOREIGN KEY (fk_teamid_team)
            REFERENCES team (id_team),
        FOREIGN KEY (fk_retrospectiveid_retrospective)
            REFERENCES retrospective (id_retrospective)
    );

    CREATE TABLE changes (
        date timestamp,
        story_points double precision,
        id_changes integer GENERATED BY DEFAULT AS IDENTITY,
        fk_role_enumid_role_enum integer NOT NULL,
        fk_role_enumid_role_enum1 integer NOT NULL,
        fk_sprintid_sprint integer NOT NULL,
        PRIMARY KEY (id_changes),
        UNIQUE (fk_role_enumid_role_enum),
        UNIQUE (fk_role_enumid_role_enum1),
        FOREIGN KEY (fk_role_enumid_role_enum)
            REFERENCES role_enum (id_role_enum),
        FOREIGN KEY (fk_role_enumid_role_enum1)
            REFERENCES role_enum (id_role_enum),
        FOREIGN KEY (fk_sprintid_sprint)
            REFERENCES sprint (id_sprint)
    );

    CREATE TABLE task (
        name varchar,
        description text,
        story_points double precision,
        acceptance_criteria_description text,
        risk int,
        priority int,
        id_task integer GENERATED BY DEFAULT AS IDENTITY,
        fk_role_enumid_role_enum integer NOT NULL,
        fk_teamid_team integer,
        fk_projectid_project integer NOT NULL,
        fk_sprintid_sprint integer,
        fk_team_memberid_team_member integer,
        PRIMARY KEY (id_task),
        UNIQUE (fk_role_enumid_role_enum),
        FOREIGN KEY (fk_role_enumid_role_enum)
            REFERENCES role_enum (id_role_enum),
        CONSTRAINT assinged_to_backlog FOREIGN KEY (fk_teamid_team)
            REFERENCES team (id_team),
        CONSTRAINT belongs FOREIGN KEY (fk_projectid_project)
            REFERENCES project (id_project),
        CONSTRAINT assinged_to FOREIGN KEY (fk_sprintid_sprint)
            REFERENCES sprint (id_sprint),
        CONSTRAINT assinged FOREIGN KEY (fk_team_memberid_team_member)
            REFERENCES team_member (id_team_member)
    );
    """)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("""
    DROP TABLE IF EXISTS task;
    DROP TABLE IF EXISTS changes;
    DROP TABLE IF EXISTS sprint;
    DROP TABLE IF EXISTS team_member;
    DROP TABLE IF EXISTS project_member;
    DROP TABLE IF EXISTS team;
    DROP TABLE IF EXISTS role;
    DROP TABLE IF EXISTS users;
    DROP TABLE IF EXISTS role_enum;
    DROP TABLE IF EXISTS retrospective;
    DROP TABLE IF EXISTS project;
    """)
